### ISSUE TITLE
Find explanation for magic numbers in IsoFiltR module

### ISSUE THREAD

**Issue by hechth** [RECETOX/MFAssignR#13]
The IsoFiltR module has some magic numbers that don't seem to have an explanation. There is some dissteration available (TODO: provide link) which contains information of those numbers. Otherwise, explanation might be somewhere in the [paper](https://doi.org/10.1016/j.envres.2020.110114) but it doesn't seem so at this point.

**Comment by hechth** [comment]
@KristinaGomoryova can you add the reference to the thesis here?

**Comment by KristinaGomoryova** [comment]
Here it is: https://core.ac.uk/download/pdf/217038739.pdf
