### ISSUE TITLE
setup CI/CD pipeline

### ISSUE THREAD

**Issue by hechth** [RECETOX/MFAssignR#3]
- Build and test the R package using the recommended GitHub CI pipeline
- Enable Codecov coverage report automation

See https://github.com/RECETOX/recetox-aplcms as an example

**Comment by zargham-ahmad** [comment]
Similar Codecov CI issue https://github.com/RECETOX/RAMClustR/issues/44 and its PR https://github.com/RECETOX/RAMClustR/pull/45
