### ISSUE TITLE
SNplot: define the cut parameter using 2 parameters: noise level and multiplier

### ISSUE THREAD

**Issue by KristinaGomoryova** [RECETOX/MFAssignR#63]
We should update the `cut` parameter, which is currently computed as `noise estimate` * `multiplier` (user provides one value, this computation is done outside galaxy). Instead, similarly to other MFAssignR functions, we should have two parameters, one for the noise estimate and one for the multiplier.

**Comment by hechth** [comment]
On the package level this is always just kept as a single parameter. The explanation is only provided in the Galaxy tools.
